version: '3.9'

services:
  api:
    build: .
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - CHANNEL_NAME=${CHANNEL_NAME}
      - NODE_ENV=production
